[mcp_servers.context7]
args = [
    "-y",
    "@upstash/context7-mcp@latest",
]
command = "npx"

[mcp_servers.shopify-dev-mcp]
args = [
    "-y",
    "@shopify/dev-mcp@latest",
]
command = "npx"

[mcp_servers.svelte]
args = [
    "-y",
    "@sveltejs/mcp",
]
command = "npx"
